language: python

services:
  - docker

before_install:
  - sed -i '/s3filestore/d' ./ckan.ini
  - docker-compose up -d
  - bin/wait-for-ckan.sh
  - "docker-compose run ckan paster --plugin=ckan db init -c /ckan.ini"
  - "docker-compose run ckan paster --plugin=ckan datastore set-permissions  -c /ckan.ini | grep -v DEBUG | docker-compose exec -T db psql --set ON_ERROR_STOP=on -U postgres"
  - "docker-compose run ckan paster --plugin=ckanext-extractor init -c /ckan.ini"
  - "echo y | docker-compose run ckan paster --plugin=ckan sysadmin add admin email="you@domain.com" name=admin password=admin -c /ckan.ini"

addons:
  hosts:
    - ckan