version: "2.2"

# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
services:
  ckan:
    build: .
    ports:
        - "80:5000"
        - "5000:5000"
    environment:
        - CKAN_REDIS_URL=redis://redis:6379/0
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN___BEAKER__SESSION__SECRET=supersecret
    env_file: env.dev
    volumes:
      - ./ckan.ini:/ckan.ini
      - ./who.ini:/who.ini
      - ckan-filestore:/var/lib/ckan/default
      - ../ckanext-satreasury/:/src/ckanext-satreasury
      - ../ckanext-discourse-sso-client/:/src/ckanext-discourse-sso-client
      - ../ckan/ckan:/src/ckan/ckan
      - ../ckan/ckanext:/src/ckan/ckanext
    command: paster serve ckan.ini
    networks:
      - ckan

  solr:
    build: ../ckan-solr-dokku
    ports:
        - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data
      - ../ckan-solr-dokku/solrconfig.xml:/opt/solr/server/solr/ckan/conf/solrconfig.xml
      - ../ckan-solr-dokku/schema.xml:/opt/solr/server/solr/ckan/conf/schema.xml
    networks:
      - ckan

  redis:
    image: redis:latest
    networks:
      - ckan

networks:
  ckan:

volumes:
  solr-data:
  ckan-filestore:
