version: "2.2"

# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
services:
  ckan:
    build: .
    links:
        - solr
        - redis
    ports:
        - "80:5000"
        - "5000:5000"
    environment:
        - CKAN_REDIS_URL=redis://redis:6379/0
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN_SITE_URL=http://ckan:5000/
        - CKAN___BEAKER__SESSION__SECRET=supersecret
    env_file: env.dev
    volumes:
      - ./ckan.ini:/ckan.ini
      - ./who.ini:/who.ini
      - ckan-filestore:/var/lib/ckan/default
      - ../ckanext-satreasury/:/src/ckanext-satreasury
      - ../ckanext-discourse-sso-client/:/src/ckanext-discourse-sso-client
    command: paster serve ckan.ini

  ckan-worker:
    build: .
    links:
        - solr
        - redis
    environment:
        - CKAN_REDIS_URL=redis://redis:6379/0
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN_SITE_URL=http://ckan:5000/
        - CKAN___BEAKER__SESSION__SECRET=supersecret
    env_file: env.dev
    volumes:
      - ./ckan.ini:/ckan.ini
      - ./who.ini:/who.ini
      - ckan-filestore:/var/lib/ckan/default
      - ../ckanext-satreasury/:/src/ckanext-satreasury
      - ../ckanext-discourse-sso-client/:/src/ckanext-discourse-sso-client
    command: paster --plugin=ckan jobs worker --config /ckan.ini

  # datapusher:
  #   # image: openup/ckan-datapusher
  #   build:
  #     context: ../ckan-datapusher-dokku/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8800:8800"

  solr:
    build: ../ckan-solr-dokku
    ports:
        - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data
      - ../ckan-solr-dokku/solrconfig.xml:/opt/solr/server/solr/ckan/conf/solrconfig.xml
      - ../ckan-solr-dokku/schema.xml:/opt/solr/server/solr/ckan/conf/schema.xml

  redis:
    image: redis:latest

volumes:
  solr-data:
  ckan-filestore:
