version: "2.2"

# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry

services:
  ckan:
    build: .
    ports:
        - "80:5000"
        - "5000:5000"
    environment:
        - CKAN_REDIS_URL=redis://redis:6379/0
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN_SITE_URL=http://ckan:5000/
        - CKAN___BEAKER__SESSION__SECRET=supersecret
        - CKAN_SQLALCHEMY_URL=postgres://ckan_default@db/ckan_default
        - CKAN_DATASTORE_WRITE_URL=postgres://ckan_default@db/datastore_default
        - CKAN_DATASTORE_READ_URL=postgres://datastore_default@db/datastore_default
        - CKAN_SATREASURY_BUILD_TRIGGER_ENABLED=False
    volumes:
      - ./bin/connect-to-postgres.py:/bin/connect-to-postgres.py
      - ./bin/wait-for-postgres.sh:/bin/wait-for-postgres.sh
      - ./ckan.ini:/ckan.ini
      - ./who.ini:/who.ini
      - ckan-filestore:/var/lib/ckan/default
    command: ["/bin/wait-for-postgres.sh", "paster", "serve", "ckan.ini"]
    depends_on:
      - solr
      - redis
      - db
      - datapusher

  ckan-worker:
    build: .
    depends_on:
      - solr
      - redis
      - db
    environment:
        - CKAN_REDIS_URL=redis://redis:6379/0
        - CKAN_SOLR_URL=http://solr:8983/solr/ckan
        - CKAN_SITE_URL=http://ckan:5000/
        - CKAN___BEAKER__SESSION__SECRET=supersecret
        - CKAN_SQLALCHEMY_URL=postgres://ckan_default@db/ckan_default
        - CKAN_DATASTORE_WRITE_URL=postgres://ckan_default@db/datastore_default
        - CKAN_DATASTORE_READ_URL=postgres://datastore_default@db/datastore_default
    volumes:
      - ./bin/connect-to-postgres.py:/bin/connect-to-postgres.py
      - ./bin/wait-for-postgres.sh:/bin/wait-for-postgres.sh
      - ./ckan.ini:/ckan.ini
      - ./who.ini:/who.ini
      - ckan-filestore:/var/lib/ckan/default
    command: ["/bin/wait-for-postgres.sh", "paster", "--plugin=ckan", "jobs", "worker", "--config", "/ckan.ini"]

  datapusher:
    build:
      context: ../ckan-datapusher
    ports:
      - "8800:8800"

  solr:
    build: ../ckan-solr-dokku
    ports:
        - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data
      - ../ckan-solr-dokku/solrconfig.xml:/opt/solr/server/solr/ckan/conf/solrconfig.xml
      - ../ckan-solr-dokku/schema.xml:/opt/solr/server/solr/ckan/conf/schema.xml

  redis:
    image: redis:latest

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
    - "5433:5432"

volumes:
  solr-data:
  ckan-filestore:
  db-data:
